import os
from dotenv import load_dotenv
load_dotenv()
MANAGER_TELEGRAM_ID = os.getenv("MANAGER_TELEGRAM_ID")
MANAGER_USER_ID = os.getenv("MANAGER_USER_ID")
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
GEMINI_API_KEY_FLASH = os.getenv("GEMINI_API_KEY_FLASH")

print(f"""1 . MANAGER_TELEGRAM_ID: {type(MANAGER_TELEGRAM_ID)}, value: {MANAGER_TELEGRAM_ID}
2 . MANAGER_USER_ID: {type(MANAGER_USER_ID)}, value: {MANAGER_USER_ID}
3 . TELEGRAM_BOT_TOKEN: {type(TELEGRAM_BOT_TOKEN)}, value: {TELEGRAM_BOT_TOKEN}
4 . GEMINI_API_KEY_FLASH: {type(GEMINI_API_KEY_FLASH)}, value: {GEMINI_API_KEY_FLASH}
""")